import NavBar from '@/components/NavBar';
import './globals.css';
import ContentPages from '@/components/ContentPages';

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-montserrat bg-primary" >
        <ContentPages all={children} />
        </body>
    </html>
  )
}
